---
title: "Untitled"
author: "bia"
date: "15/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(magrittr)
library(ggplot2)

dataset_corpus_raw <- readr::read_rds("data/dataset_corpus_raw.Rds")

head(dataset_corpus_raw)
```


```{r}
united_clean_text <- dataset_corpus_raw %>%
  dplyr::mutate(
    texto = stringr::str_replace_all(text, "_", " "),
    texto = stringr::str_squish(texto)
    
  ) %>%
  dplyr::mutate(ano = lubridate::year(data_reuniao)) %>%
  dplyr::mutate(
    crise = dplyr::case_when(
      ano %in% c(2008:2012) ~  "antes_crise" ,
      ano %in% c(2013:2015) ~  "durante_crise" ,
      ano %in% c(2016:2020) ~  "pos_crise" ,
      TRUE ~ "outros"
      
    )
  )

head(united_clean_text)

small_dataset <-   united_clean_text %>%
  dplyr::select(comite, ano, crise, texto) 


head(small_dataset)

# deletando arquivos intermediarios para nao ficar pesado
rm(dataset_corpus_raw)
rm(united_clean_text)
```


## Bigrams

```{r}
tokens_bigram <- small_dataset %>%
  tidytext::unnest_tokens(bigram, texto, token = "ngrams", n = 2)


# deletando arquivos intermediarios para nao ficar pesado
rm(small_dataset)
```


```{r}
bigrams_separated <- tokens_bigram %>%
  tidyr::separate(bigram, c("word1", "word2"), sep = " ")

# deletando arquivos intermediarios para nao ficar pesado
rm(tokens_bigram)


source("stop_words.R", encoding = "UTF-8")


bigrams_filtered_united <- bigrams_separated %>%
  dplyr::filter(!word1 %in% stopwords_br$word) %>%
  dplyr::filter(!word2 %in% stopwords_br$word) %>%
  dplyr::mutate(
    word1 = stringr::str_replace_all(word1, pattern = "[0-9]+", replacement = NA_character_),
    
    word2 = stringr::str_replace_all(word2, pattern = "[0-9]+", replacement = NA_character_)
  ) %>%
  tidyr::drop_na() %>%
  tidyr::unite(bigram, word1, word2, sep = " ") %>%
  dplyr::filter(!bigram %in% stopwords_br_bigram$word) %>%
  dplyr::mutate(
    bigram = dplyr::case_when(
      bigram == "câmara técnica" ~ "câmara(s) técnica(s)",
      bigram == "câmaras técnicas" ~ "câmara(s) técnica(s)",
      TRUE ~ bigram
    )
  )



# new bigram counts:
bigram_counts <- bigrams_filtered_united  %>%
  dplyr::group_by(crise, comite) %>%
  dplyr::count(bigram, sort = TRUE)

# bigram_counts

```

```{r}
#devtools::install_github("thomasp85/patchwork")
library(patchwork)

gerar_grafico_comite <- function(comite_string){
  
bigrams <- bigram_counts %>%
  dplyr::filter(
    comite == {{comite_string}},
                crise != "outros") %>%
  dplyr::ungroup() 
  

gerar_grafico_crise <- function(qual_crise){
  bigrams  %>% 
  dplyr::filter(crise == {{qual_crise}}) %>%
   dplyr::top_n(10) %>% 
  dplyr::mutate(bigram = reorder(bigram, n)) %>%
  ggplot() +
  geom_col(aes(x = bigram, y = n), fill = "lightblue") +
  coord_flip() +
 # facet_grid(comite ~ crise) +
  theme_bw()

}
 
antes_crise <- gerar_grafico_crise("antes_crise") +
   labs(x = "Bigram", y = "", title = "2008-2021") 

durante_crise <- gerar_grafico_crise("durante_crise") +
   labs(y = "Number of occurrences", x = "", title = "2013-2015") 

pos_crise <- gerar_grafico_crise("pos_crise")+
   labs(y = "", x = "", title = "2016-2020") 

grafico_final <- (antes_crise + durante_crise + pos_crise)  + 
  plot_annotation(title = paste("Water Basin Committee", comite_string),
                  caption = "Data collected in Dec 08th 2020")

comite_nome <- comite_string %>%  abjutils::rm_accent() %>% stringr::str_replace_all("/", "")%>%
  stringr::str_replace_all(" ", "_")

grafico_final %>% ggsave(filename = paste0(comite_nome, ".png"), 
  path = "img/", device = "png", width = 12, height = 6)

}

gerar_grafico_comite("Alto Tietê") # ok sw
gerar_grafico_comite("Baixada Santista")# ok sw
gerar_grafico_comite("Piracicaba / Capivari / Jundiaí") # ok sw
gerar_grafico_comite("Sorocaba e Médio Tietê")
gerar_grafico_comite("Litoral Norte")
gerar_grafico_comite("Mogi-Guaçu")
gerar_grafico_comite("Ribeira do Iguape e Litoral Sul")

```

